//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOsenka
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestHeader", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.RequestModels")]
    public partial class RequestHeader : object
    {
        
        private string PasswordField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceZoneMedianValueRequest", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.RequestModels")]
    public partial class PriceZoneMedianValueRequest : object
    {
        
        private string AddressField;
        
        private string CityField;
        
        private long CityIdField;
        
        private long EgovStreetIdField;
        
        private string EgovStreetNameField;
        
        private string HouseNumberField;
        
        private decimal LandSquareField;
        
        private long RealtyTypeField;
        
        private long RoomNumberField;
        
        private decimal TotalSquareField;
        
        private long WallMaterialField;
        
        private int YearBuiltField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CityId
        {
            get
            {
                return this.CityIdField;
            }
            set
            {
                this.CityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EgovStreetId
        {
            get
            {
                return this.EgovStreetIdField;
            }
            set
            {
                this.EgovStreetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EgovStreetName
        {
            get
            {
                return this.EgovStreetNameField;
            }
            set
            {
                this.EgovStreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string HouseNumber
        {
            get
            {
                return this.HouseNumberField;
            }
            set
            {
                this.HouseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LandSquare
        {
            get
            {
                return this.LandSquareField;
            }
            set
            {
                this.LandSquareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RealtyType
        {
            get
            {
                return this.RealtyTypeField;
            }
            set
            {
                this.RealtyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RoomNumber
        {
            get
            {
                return this.RoomNumberField;
            }
            set
            {
                this.RoomNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalSquare
        {
            get
            {
                return this.TotalSquareField;
            }
            set
            {
                this.TotalSquareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WallMaterial
        {
            get
            {
                return this.WallMaterialField;
            }
            set
            {
                this.WallMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearBuilt
        {
            get
            {
                return this.YearBuiltField;
            }
            set
            {
                this.YearBuiltField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractResponse", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.PriceZoneInfoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.MedianValueResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.CitySettlementResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.WallMaterialResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.PriceZoneResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.StreetEgovResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.EgovResponseOfEgovATSTypeeEf8Gzh8))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.EgovResponseOfEgovATSeEf8Gzh8))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.EgovResponseOfEgovGEONIMTypeeEf8Gzh8))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.EgovResponseOfEgovGEONIMeEf8Gzh8))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.PropertyPriceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.PriceZoneMedianValueResponse))]
    public partial class AbstractResponse : object
    {
        
        private string ErrorMessageField;
        
        private string RequestGuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestGuid
        {
            get
            {
                return this.RequestGuidField;
            }
            set
            {
                this.RequestGuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceZoneInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class PriceZoneInfoResponse : ProOsenka.AbstractResponse
    {
        
        private string PriceZoneDescField;
        
        private long PriceZoneIDField;
        
        private string PriceZoneNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceZoneDesc
        {
            get
            {
                return this.PriceZoneDescField;
            }
            set
            {
                this.PriceZoneDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PriceZoneID
        {
            get
            {
                return this.PriceZoneIDField;
            }
            set
            {
                this.PriceZoneIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceZoneNum
        {
            get
            {
                return this.PriceZoneNumField;
            }
            set
            {
                this.PriceZoneNumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedianValueResponse", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class MedianValueResponse : ProOsenka.AbstractResponse
    {
        
        private ProOsenka.MarketValueReport[] AnalogsField;
        
        private decimal AverageUnitPriceField;
        
        private int BuiltYearField;
        
        private string CityField;
        
        private long IdField;
        
        private decimal KZTPriceField;
        
        private long NumberOfRoomsField;
        
        private long RealtyTypeField;
        
        private string RealtyTypeStrField;
        
        private System.DateTime ReportDateField;
        
        private decimal TotalSquareField;
        
        private string WallMaterialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProOsenka.MarketValueReport[] Analogs
        {
            get
            {
                return this.AnalogsField;
            }
            set
            {
                this.AnalogsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AverageUnitPrice
        {
            get
            {
                return this.AverageUnitPriceField;
            }
            set
            {
                this.AverageUnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuiltYear
        {
            get
            {
                return this.BuiltYearField;
            }
            set
            {
                this.BuiltYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KZTPrice
        {
            get
            {
                return this.KZTPriceField;
            }
            set
            {
                this.KZTPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NumberOfRooms
        {
            get
            {
                return this.NumberOfRoomsField;
            }
            set
            {
                this.NumberOfRoomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RealtyType
        {
            get
            {
                return this.RealtyTypeField;
            }
            set
            {
                this.RealtyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealtyTypeStr
        {
            get
            {
                return this.RealtyTypeStrField;
            }
            set
            {
                this.RealtyTypeStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReportDate
        {
            get
            {
                return this.ReportDateField;
            }
            set
            {
                this.ReportDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalSquare
        {
            get
            {
                return this.TotalSquareField;
            }
            set
            {
                this.TotalSquareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WallMaterial
        {
            get
            {
                return this.WallMaterialField;
            }
            set
            {
                this.WallMaterialField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CitySettlementResponse", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class CitySettlementResponse : ProOsenka.AbstractResponse
    {
        
        private ProOsenka.IdNameClass[] citiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProOsenka.IdNameClass[] cities
        {
            get
            {
                return this.citiesField;
            }
            set
            {
                this.citiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WallMaterialResponse", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class WallMaterialResponse : ProOsenka.AbstractResponse
    {
        
        private ProOsenka.IdNameClass[] wallMaterialsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProOsenka.IdNameClass[] wallMaterials
        {
            get
            {
                return this.wallMaterialsField;
            }
            set
            {
                this.wallMaterialsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceZoneResponse", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class PriceZoneResponse : ProOsenka.AbstractResponse
    {
        
        private ProOsenka.IdNameWithNumClass[] priceZonesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProOsenka.IdNameWithNumClass[] priceZones
        {
            get
            {
                return this.priceZonesField;
            }
            set
            {
                this.priceZonesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StreetEgovResponse", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class StreetEgovResponse : ProOsenka.AbstractResponse
    {
        
        private ProOsenka.StreetEgov[] streetsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProOsenka.StreetEgov[] streets
        {
            get
            {
                return this.streetsField;
            }
            set
            {
                this.streetsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgovResponseOfEgovATSTypeeEf8Gzh8", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class EgovResponseOfEgovATSTypeeEf8Gzh8 : ProOsenka.AbstractResponse
    {
        
        private ProOsenka.EgovATSType[] listField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProOsenka.EgovATSType[] list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgovResponseOfEgovATSeEf8Gzh8", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class EgovResponseOfEgovATSeEf8Gzh8 : ProOsenka.AbstractResponse
    {
        
        private ProOsenka.EgovATS[] listField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProOsenka.EgovATS[] list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgovResponseOfEgovGEONIMTypeeEf8Gzh8", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class EgovResponseOfEgovGEONIMTypeeEf8Gzh8 : ProOsenka.AbstractResponse
    {
        
        private ProOsenka.EgovGEONIMType[] listField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProOsenka.EgovGEONIMType[] list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgovResponseOfEgovGEONIMeEf8Gzh8", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class EgovResponseOfEgovGEONIMeEf8Gzh8 : ProOsenka.AbstractResponse
    {
        
        private ProOsenka.EgovGEONIM[] listField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProOsenka.EgovGEONIM[] list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyPriceResponse", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class PropertyPriceResponse : ProOsenka.AbstractResponse
    {
        
        private int BuiltYearField;
        
        private long IdField;
        
        private decimal PriceField;
        
        private int PriceTypeField;
        
        private long RealtyTypeField;
        
        private System.DateTime ReportDateField;
        
        private string WallMaterialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuiltYear
        {
            get
            {
                return this.BuiltYearField;
            }
            set
            {
                this.BuiltYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PriceType
        {
            get
            {
                return this.PriceTypeField;
            }
            set
            {
                this.PriceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RealtyType
        {
            get
            {
                return this.RealtyTypeField;
            }
            set
            {
                this.RealtyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReportDate
        {
            get
            {
                return this.ReportDateField;
            }
            set
            {
                this.ReportDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WallMaterial
        {
            get
            {
                return this.WallMaterialField;
            }
            set
            {
                this.WallMaterialField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceZoneMedianValueResponse", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class PriceZoneMedianValueResponse : ProOsenka.AbstractResponse
    {
        
        private ProOsenka.MarketValueReport[] AnalogsField;
        
        private decimal AverageUnitPriceField;
        
        private int BuiltYearField;
        
        private string CityField;
        
        private long IdField;
        
        private decimal KZTPriceField;
        
        private long NumberOfRoomsField;
        
        private string PriceZoneDescField;
        
        private string PriceZoneNumField;
        
        private long RealtyTypeField;
        
        private string RealtyTypeStrField;
        
        private System.DateTime ReportDateField;
        
        private decimal TotalSquareField;
        
        private string WallMaterialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProOsenka.MarketValueReport[] Analogs
        {
            get
            {
                return this.AnalogsField;
            }
            set
            {
                this.AnalogsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AverageUnitPrice
        {
            get
            {
                return this.AverageUnitPriceField;
            }
            set
            {
                this.AverageUnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuiltYear
        {
            get
            {
                return this.BuiltYearField;
            }
            set
            {
                this.BuiltYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KZTPrice
        {
            get
            {
                return this.KZTPriceField;
            }
            set
            {
                this.KZTPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NumberOfRooms
        {
            get
            {
                return this.NumberOfRoomsField;
            }
            set
            {
                this.NumberOfRoomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceZoneDesc
        {
            get
            {
                return this.PriceZoneDescField;
            }
            set
            {
                this.PriceZoneDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceZoneNum
        {
            get
            {
                return this.PriceZoneNumField;
            }
            set
            {
                this.PriceZoneNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RealtyType
        {
            get
            {
                return this.RealtyTypeField;
            }
            set
            {
                this.RealtyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealtyTypeStr
        {
            get
            {
                return this.RealtyTypeStrField;
            }
            set
            {
                this.RealtyTypeStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReportDate
        {
            get
            {
                return this.ReportDateField;
            }
            set
            {
                this.ReportDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalSquare
        {
            get
            {
                return this.TotalSquareField;
            }
            set
            {
                this.TotalSquareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WallMaterial
        {
            get
            {
                return this.WallMaterialField;
            }
            set
            {
                this.WallMaterialField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketValueReport", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.Model")]
    public partial class MarketValueReport : object
    {
        
        private string AdLinkField;
        
        private string AddressField;
        
        private long AnalogIDField;
        
        private decimal AverageUnitPriceField;
        
        private int BuiltYearField;
        
        private string CityField;
        
        private string ClassField;
        
        private string JComplexField;
        
        private decimal KZTPriceField;
        
        private string RealtyTypeField;
        
        private string RealtyTypeIdField;
        
        private System.DateTime ReportDateField;
        
        private string RoomNumberField;
        
        private decimal TotalSquareField;
        
        private string WallMaterialField;
        
        private System.Nullable<System.DateTime> createOnField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdLink
        {
            get
            {
                return this.AdLinkField;
            }
            set
            {
                this.AdLinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AnalogID
        {
            get
            {
                return this.AnalogIDField;
            }
            set
            {
                this.AnalogIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AverageUnitPrice
        {
            get
            {
                return this.AverageUnitPriceField;
            }
            set
            {
                this.AverageUnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuiltYear
        {
            get
            {
                return this.BuiltYearField;
            }
            set
            {
                this.BuiltYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class
        {
            get
            {
                return this.ClassField;
            }
            set
            {
                this.ClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JComplex
        {
            get
            {
                return this.JComplexField;
            }
            set
            {
                this.JComplexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KZTPrice
        {
            get
            {
                return this.KZTPriceField;
            }
            set
            {
                this.KZTPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealtyType
        {
            get
            {
                return this.RealtyTypeField;
            }
            set
            {
                this.RealtyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealtyTypeId
        {
            get
            {
                return this.RealtyTypeIdField;
            }
            set
            {
                this.RealtyTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReportDate
        {
            get
            {
                return this.ReportDateField;
            }
            set
            {
                this.ReportDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomNumber
        {
            get
            {
                return this.RoomNumberField;
            }
            set
            {
                this.RoomNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalSquare
        {
            get
            {
                return this.TotalSquareField;
            }
            set
            {
                this.TotalSquareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WallMaterial
        {
            get
            {
                return this.WallMaterialField;
            }
            set
            {
                this.WallMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> createOn
        {
            get
            {
                return this.createOnField;
            }
            set
            {
                this.createOnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdNameClass", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProOsenka.IdNameWithNumClass))]
    public partial class IdNameClass : object
    {
        
        private long IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdNameWithNumClass", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class IdNameWithNumClass : ProOsenka.IdNameClass
    {
        
        private string NumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num
        {
            get
            {
                return this.NumField;
            }
            set
            {
                this.NumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StreetEgov", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class StreetEgov : object
    {
        
        private long CityIdField;
        
        private long EgovIdField;
        
        private long IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CityId
        {
            get
            {
                return this.CityIdField;
            }
            set
            {
                this.CityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EgovId
        {
            get
            {
                return this.EgovIdField;
            }
            set
            {
                this.EgovIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgovATSType", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class EgovATSType : object
    {
        
        private long IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgovATS", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class EgovATS : object
    {
        
        private string CatoField;
        
        private long IDField;
        
        private string NameField;
        
        private long ParentIDField;
        
        private long TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cato
        {
            get
            {
                return this.CatoField;
            }
            set
            {
                this.CatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParentID
        {
            get
            {
                return this.ParentIDField;
            }
            set
            {
                this.ParentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgovGEONIMType", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class EgovGEONIMType : object
    {
        
        private long IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgovGEONIM", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.ResponseModels")]
    public partial class EgovGEONIM : object
    {
        
        private long IDField;
        
        private string NameField;
        
        private long ParentIDField;
        
        private int TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParentID
        {
            get
            {
                return this.ParentIDField;
            }
            set
            {
                this.ParentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceZoneRequest", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.RequestModels")]
    public partial class PriceZoneRequest : object
    {
        
        private string AddressField;
        
        private string CityField;
        
        private long CityIdField;
        
        private long EgovStreetIdField;
        
        private string EgovStreetNameField;
        
        private string HouseNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CityId
        {
            get
            {
                return this.CityIdField;
            }
            set
            {
                this.CityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EgovStreetId
        {
            get
            {
                return this.EgovStreetIdField;
            }
            set
            {
                this.EgovStreetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EgovStreetName
        {
            get
            {
                return this.EgovStreetNameField;
            }
            set
            {
                this.EgovStreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string HouseNumber
        {
            get
            {
                return this.HouseNumberField;
            }
            set
            {
                this.HouseNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceZoneNewRequest", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.RequestModels")]
    public partial class PriceZoneNewRequest : object
    {
        
        private string AddressField;
        
        private string HouseNumberField;
        
        private long StreetEgovIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string HouseNumber
        {
            get
            {
                return this.HouseNumberField;
            }
            set
            {
                this.HouseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long StreetEgovId
        {
            get
            {
                return this.StreetEgovIdField;
            }
            set
            {
                this.StreetEgovIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedianValueRequest", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.RequestModels")]
    public partial class MedianValueRequest : object
    {
        
        private decimal LandSquareField;
        
        private long PriceZoneIdField;
        
        private long RealtyTypeField;
        
        private long RoomNumberField;
        
        private decimal TotalSquareField;
        
        private long WallMaterialField;
        
        private int YearBuiltField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LandSquare
        {
            get
            {
                return this.LandSquareField;
            }
            set
            {
                this.LandSquareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PriceZoneId
        {
            get
            {
                return this.PriceZoneIdField;
            }
            set
            {
                this.PriceZoneIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RealtyType
        {
            get
            {
                return this.RealtyTypeField;
            }
            set
            {
                this.RealtyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RoomNumber
        {
            get
            {
                return this.RoomNumberField;
            }
            set
            {
                this.RoomNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalSquare
        {
            get
            {
                return this.TotalSquareField;
            }
            set
            {
                this.TotalSquareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WallMaterial
        {
            get
            {
                return this.WallMaterialField;
            }
            set
            {
                this.WallMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearBuilt
        {
            get
            {
                return this.YearBuiltField;
            }
            set
            {
                this.YearBuiltField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyPriceRequest", Namespace="http://schemas.datacontract.org/2004/07/AppraisalService.RequestModels")]
    public partial class PropertyPriceRequest : object
    {
        
        private long AtsIDField;
        
        private long GeonimIDField;
        
        private string HouseNumberField;
        
        private long RealtyTypeField;
        
        private long RoomNumberField;
        
        private long WallMaterialField;
        
        private int YearBuiltField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long AtsID
        {
            get
            {
                return this.AtsIDField;
            }
            set
            {
                this.AtsIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long GeonimID
        {
            get
            {
                return this.GeonimIDField;
            }
            set
            {
                this.GeonimIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseNumber
        {
            get
            {
                return this.HouseNumberField;
            }
            set
            {
                this.HouseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RealtyType
        {
            get
            {
                return this.RealtyTypeField;
            }
            set
            {
                this.RealtyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RoomNumber
        {
            get
            {
                return this.RoomNumberField;
            }
            set
            {
                this.RoomNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WallMaterial
        {
            get
            {
                return this.WallMaterialField;
            }
            set
            {
                this.WallMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearBuilt
        {
            get
            {
                return this.YearBuiltField;
            }
            set
            {
                this.YearBuiltField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProOsenka.IAppraisal")]
    public interface IAppraisal
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetPZMedianValue", ReplyAction="http://tempuri.org/IAppraisal/GetPZMedianValueResponse")]
        System.Threading.Tasks.Task<ProOsenka.PriceZoneMedianValueResponse> GetPZMedianValueAsync(ProOsenka.RequestHeader header, ProOsenka.PriceZoneMedianValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetPriceZone", ReplyAction="http://tempuri.org/IAppraisal/GetPriceZoneResponse")]
        System.Threading.Tasks.Task<ProOsenka.PriceZoneInfoResponse> GetPriceZoneAsync(ProOsenka.RequestHeader header, ProOsenka.PriceZoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetPriceZoneNew", ReplyAction="http://tempuri.org/IAppraisal/GetPriceZoneNewResponse")]
        System.Threading.Tasks.Task<ProOsenka.PriceZoneInfoResponse> GetPriceZoneNewAsync(ProOsenka.RequestHeader header, ProOsenka.PriceZoneNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetMedianValueByPriceZone", ReplyAction="http://tempuri.org/IAppraisal/GetMedianValueByPriceZoneResponse")]
        System.Threading.Tasks.Task<ProOsenka.MedianValueResponse> GetMedianValueByPriceZoneAsync(ProOsenka.RequestHeader header, ProOsenka.MedianValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetCities", ReplyAction="http://tempuri.org/IAppraisal/GetCitiesResponse")]
        System.Threading.Tasks.Task<ProOsenka.CitySettlementResponse> GetCitiesAsync(ProOsenka.RequestHeader header);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetWallMaterials", ReplyAction="http://tempuri.org/IAppraisal/GetWallMaterialsResponse")]
        System.Threading.Tasks.Task<ProOsenka.WallMaterialResponse> GetWallMaterialsAsync(ProOsenka.RequestHeader header);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetPriceZones", ReplyAction="http://tempuri.org/IAppraisal/GetPriceZonesResponse")]
        System.Threading.Tasks.Task<ProOsenka.PriceZoneResponse> GetPriceZonesAsync(ProOsenka.RequestHeader header, long CityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetEgovStreets", ReplyAction="http://tempuri.org/IAppraisal/GetEgovStreetsResponse")]
        System.Threading.Tasks.Task<ProOsenka.StreetEgovResponse> GetEgovStreetsAsync(ProOsenka.RequestHeader header, long CityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetEgovATSType", ReplyAction="http://tempuri.org/IAppraisal/GetEgovATSTypeResponse")]
        System.Threading.Tasks.Task<ProOsenka.EgovResponseOfEgovATSTypeeEf8Gzh8> GetEgovATSTypeAsync(ProOsenka.RequestHeader header);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetEgovATS", ReplyAction="http://tempuri.org/IAppraisal/GetEgovATSResponse")]
        System.Threading.Tasks.Task<ProOsenka.EgovResponseOfEgovATSeEf8Gzh8> GetEgovATSAsync(ProOsenka.RequestHeader header, long atsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetEgovGEONIMType", ReplyAction="http://tempuri.org/IAppraisal/GetEgovGEONIMTypeResponse")]
        System.Threading.Tasks.Task<ProOsenka.EgovResponseOfEgovGEONIMTypeeEf8Gzh8> GetEgovGEONIMTypeAsync(ProOsenka.RequestHeader header);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetEgovGEONIM", ReplyAction="http://tempuri.org/IAppraisal/GetEgovGEONIMResponse")]
        System.Threading.Tasks.Task<ProOsenka.EgovResponseOfEgovGEONIMeEf8Gzh8> GetEgovGEONIMAsync(ProOsenka.RequestHeader header, long atsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppraisal/GetPropertyPrice", ReplyAction="http://tempuri.org/IAppraisal/GetPropertyPriceResponse")]
        System.Threading.Tasks.Task<ProOsenka.PropertyPriceResponse> GetPropertyPriceAsync(ProOsenka.RequestHeader header, ProOsenka.PropertyPriceRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IAppraisalChannel : ProOsenka.IAppraisal, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AppraisalClient : System.ServiceModel.ClientBase<ProOsenka.IAppraisal>, ProOsenka.IAppraisal
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AppraisalClient() : 
                base(AppraisalClient.GetDefaultBinding(), AppraisalClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAppraisal.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraisalClient(EndpointConfiguration endpointConfiguration) : 
                base(AppraisalClient.GetBindingForEndpoint(endpointConfiguration), AppraisalClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraisalClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AppraisalClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraisalClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AppraisalClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraisalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ProOsenka.PriceZoneMedianValueResponse> GetPZMedianValueAsync(ProOsenka.RequestHeader header, ProOsenka.PriceZoneMedianValueRequest request)
        {
            return base.Channel.GetPZMedianValueAsync(header, request);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.PriceZoneInfoResponse> GetPriceZoneAsync(ProOsenka.RequestHeader header, ProOsenka.PriceZoneRequest request)
        {
            return base.Channel.GetPriceZoneAsync(header, request);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.PriceZoneInfoResponse> GetPriceZoneNewAsync(ProOsenka.RequestHeader header, ProOsenka.PriceZoneNewRequest request)
        {
            return base.Channel.GetPriceZoneNewAsync(header, request);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.MedianValueResponse> GetMedianValueByPriceZoneAsync(ProOsenka.RequestHeader header, ProOsenka.MedianValueRequest request)
        {
            return base.Channel.GetMedianValueByPriceZoneAsync(header, request);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.CitySettlementResponse> GetCitiesAsync(ProOsenka.RequestHeader header)
        {
            return base.Channel.GetCitiesAsync(header);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.WallMaterialResponse> GetWallMaterialsAsync(ProOsenka.RequestHeader header)
        {
            return base.Channel.GetWallMaterialsAsync(header);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.PriceZoneResponse> GetPriceZonesAsync(ProOsenka.RequestHeader header, long CityId)
        {
            return base.Channel.GetPriceZonesAsync(header, CityId);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.StreetEgovResponse> GetEgovStreetsAsync(ProOsenka.RequestHeader header, long CityId)
        {
            return base.Channel.GetEgovStreetsAsync(header, CityId);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.EgovResponseOfEgovATSTypeeEf8Gzh8> GetEgovATSTypeAsync(ProOsenka.RequestHeader header)
        {
            return base.Channel.GetEgovATSTypeAsync(header);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.EgovResponseOfEgovATSeEf8Gzh8> GetEgovATSAsync(ProOsenka.RequestHeader header, long atsID)
        {
            return base.Channel.GetEgovATSAsync(header, atsID);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.EgovResponseOfEgovGEONIMTypeeEf8Gzh8> GetEgovGEONIMTypeAsync(ProOsenka.RequestHeader header)
        {
            return base.Channel.GetEgovGEONIMTypeAsync(header);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.EgovResponseOfEgovGEONIMeEf8Gzh8> GetEgovGEONIMAsync(ProOsenka.RequestHeader header, long atsID)
        {
            return base.Channel.GetEgovGEONIMAsync(header, atsID);
        }
        
        public System.Threading.Tasks.Task<ProOsenka.PropertyPriceResponse> GetPropertyPriceAsync(ProOsenka.RequestHeader header, ProOsenka.PropertyPriceRequest request)
        {
            return base.Channel.GetPropertyPriceAsync(header, request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAppraisal))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAppraisal))
            {
                return new System.ServiceModel.EndpointAddress("http://pro-osenka.kz:81/AppraisalService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AppraisalClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAppraisal);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AppraisalClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAppraisal);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAppraisal,
        }
    }
}
